### PR TITLE
Added CRDS to STIS notebooks requirements

### PR DESCRIPTION
**Pull request by sean-lockwood**
Modifying requirements files for STIS `cross-correlation.ipynb` and `calstis_2d_ccd.ipynb` to add the CRDS package.  Hopefully this will allow `calstis` to access reference files when reprocessing data.

These are pre-existing notebooks.

### CODE REVIEW

**Comment by sean-lockwood** [comment]
@haticekaratay -
How can we get this to run on the regression suite on the two notebooks?

cc: @Jackie-Brown

**Comment by sean-lockwood** [comment]
@haticekaratay -

Looks like the `requirements.txt` files do not trigger the CI:

https://github.com/spacetelescope/hst_notebooks/blob/main/.github/workflows/ci_runner.yml#L15

**Comment by haticekaratay** [comment]
> @haticekaratay -
> 
> Looks like the `requirements.txt` and `pre-requirements.sh` files do not trigger the CI:
> 
> https://github.com/spacetelescope/hst_notebooks/blob/main/.github/workflows/ci_runner.yml#L15

Thanks, @sean-lockwood, for working on this. It's triggered by an edit to the notebook due to the way the CI is set up. I suggest making a small change to the notebook.

**Comment by sean-lockwood** [comment]
@Jackie-Brown -
Would you mind making the minor changes to the two notebooks, at your convenience?

**Comment by Jackie-Brown** [comment]
@sean-lockwood  made some minor text changes and checks are now running

**Review by haticekaratay — APPROVED** [review]
Thank you, both @sean-lockwood  and @Jackie-Brown, for working on these notebooks.

**Pull request merged**
