### PR TITLE
added findsat_mrt demo to satellite mask notebook

### PR DESCRIPTION
**Pull request by dvstark**
I have added an example to mask_satellite.ipynb showing how to mask satellite trails with the new module acstools.findsat_mrt. The previous example is still there. I also confirmed the notebook runs start to finish.

### CODE REVIEW

**Comment by dvstark** [comment]
This may have failed if it doesn't pull the most recent version of acstools that fixed a bug in acstools.satdet (3.6.0 still has this bug, I think)

**Comment by camipacifici** [comment]
@dulude @haticekaratay this does not need to go through formal technical review at this time. Feel free merge when ready.

**Comment by haticekaratay** [comment]
> @dulude @haticekaratay this does not need to go through formal technical review at this time. Feel free merge when ready.
Thanks @camipacifici!
@dvstark Please resolve the conflicts you see with this notebook so we can proceed with a merge. Thanks!

**Comment by dulude** [comment]
Please rebase your code with main to update the pep8 checker code to the latest version. This will allow a workflow to perform PEP8 style check on the python code imbedded in the notebook.

**Comment by dvstark** [comment]
Hi all, working on this, but when rebasing my branch with main, I am struggling to resolve the merge conflicts in the jupyter-notebook itself. Is there a recommended tool/method to do so? Apologies for my lack of git expertise here.

**Comment by haticekaratay** [comment]
Hi @dvstark, If you navigate to the bottom of this conversation, you will find the following:
image
In order to address conflicts with the main, please click on the "web editor" link. This will show you the conflicts, and you can choose the ones you want to keep. Afterward, you can proceed with resolving the conflicts.

**Comment by haticekaratay** [comment]
Thank you, @dvstark, for resolving the conflicts. The notebook will be merged in its current state and added to the queue for a technical review to address any failing actions.

**Pull request merged**
