### PR TITLE
Corrected HTML Link

### PR DESCRIPTION
**Pull request by mrevalski**
The link to the revised WFPC2 drizzling notebook in the README.md file has been corrected from *.ipynb to an *.html extension.

### CODE REVIEW

**Comment by gibsongreen** [comment]
> Hi @gibsongreen, this request corrects a minor error in the URL for the revised WFPC2 drizzling notebook that was merged in PR #333. However, I receive a 404 error when trying to navigate to the HTML page. I do not see my new branch listed under the ci_manual_single_merge_generate workflow request, so it may need to be generated via another manual workflow? Thank you!

If I understand correctly, I believe we need to retrigger the CI to run on the `drizzle_wfpc2.ipynb` notebook from PR #333. I made a trivial change that has no consequence to the notebook, which will fire off the CI again and this should result in the generation of the HTML page.

**Comment by mrevalski** [comment]
Thank you! Can you or @haticekaratay merge this request into main as your time allows? 🙂

**Review by gibsongreen — APPROVED** [review]
This PR is a 1 line change to update the file format type so we can properly render the generated HTML file, ready to merge!

**Comment by mrevalski** [comment]
Hi @gibsongreen, I checked the HST Notebooks [DrizzlePac Readme](https://spacetelescope.github.io/hst_notebooks/notebooks/DrizzlePac/README.html) page, and I am not seeing this update. At the moment, hovering over the "Drizzling new WFPC2 flt data products" text still shows it linked to the *.ipynb instead of the HTML page. Do you have suggestions on how to resolve this? I tried running the [ci_manual_html_deploy](https://github.com/spacetelescope/hst_notebooks/actions/workflows/ci_manual_html_deploy.yml) without any affect. Thank you for your time and help!

**Comment by mrevalski** [comment]
Thank you for your assistance @gibsongreen. We are planning to advertise this revised notebook in a Space Telescope Announcement Newsletter (STAN) article led by @mackjenn this Friday, as well as at AAS next week, so this is relatively high priority for our team. Please let us know if we can be of help, or if you require any additional information. Thank you again!

**Comment by gibsongreen** [comment]
> Thank you for your assistance @gibsongreen. We are planning to advertise this revised notebook in a Space Telescope Announcement Newsletter (STAN) article led by @mackjenn this Friday, as well as at AAS next week, so this is relatively high priority for our team. Please let us know if we can be of help, or if you require any additional information. Thank you again!

Hi @mrevalski, I believe a have found the source of the issue. It appears that back in June, this notebook had been removed from the hst_notebooks _toc.yml file:
https://github.com/spacetelescope/hst_notebooks/blob/c54c4579f5c255e19d77a2f46048ecaa346c5099/_toc.yml#L43

I will open a PR to uncomment this line and another trivial change to the notebook, merging should retrigger the html deployment and update the docs 🤞.

**Comment by mrevalski** [comment]
Hi @gibsongreen, I wanted to follow-up on this pull request. When clicking the link on the main DrizzlePac HTML webpage, it still redirects users to a link with a *.ipynb extension, rather than the correct *.html version. The HTML link itself is now correctly working after your other fixes to the TOC. Please let us know if there's anything we can do to assist? Thank you for your help!

**Comment by gibsongreen** [comment]
> Hi @gibsongreen, I wanted to follow-up on this pull request. When clicking the link on the main DrizzlePac HTML webpage, it still redirects users to a link with a *.ipynb extension, rather than the correct *.html version. The HTML link itself is now correctly working after your other fixes to the TOC. Please let us know if there's anything we can do to assist? Thank you for your help!

@mrevalski Sorry about the delay! I have confirmed with Hatice that this is indeed a bug within the CI deployment. I have opened a Help Desk ticket to the CI team to resolve this (I have added you to the watch list of this ticket).

**Comment by mrevalski** [comment]
The open issue with this PR has been resolved, with thanks to @mgough-970 for finding a solution. This is now closed.

**Pull request merged**
