### PR TITLE
Fix WFC3 Filter Transformations Notebook

### PR DESCRIPTION
**Pull request by FDauphin**
This notebook checklist has been made available to us by the [Notebooks For All team](https://github.com/Iota-School/notebooks-for-all/blob/main/resources/event-hackathon/notebook-authoring-checklist.md).
Its purpose is to serve as a guide for both the notebook author and the technical reviewer highlighting critical aspects to consider when striving to develop an accessible and effective notebook.

### The First Cell

- [ ] The title of the notebook in a first-level heading (eg. `<h1>` or `# in markdown`).
- [ ] A brief description of the notebook.
- [ ] A table of contents in an [ordered list](https://www.markdownguide.org/basic-syntax/#ordered-lists) (`1., 2.,` etc. in Markdown).
- [ ] The author(s) and affiliation(s) (if relevant).
- [ ] The date first published.
- [ ] The date last edited (if relevant).
- [ ] A link to the notebook's source(s) (if relevant).

### The Rest of the Cells

- [ ] There is only one H1 (`#` in Markdown) used in the notebook.
- [ ] The notebook uses other [heading tags](https://www.markdownguide.org/basic-syntax/#headings) in order (meaning it does not skip numbers). 

## Text

- [ ] All link text is descriptive. It tells users where they will be taken if they open the link.
- [ ] All acronyms are defined at least the first time they are used. 
- [ ] Field-specific/specialized terms are used when needed, but not excessively.

## Code

- [ ] Code sections are introduced and explained before they appear in the notebook. This can be fulfilled with a heading in a prior Markdown cell, a sentence preceding it, or a code comment in the code section.
- [ ] Code has explanatory comments (if relevant). This is most important for long sections of code.
- [ ] If the author has control over the syntax highlighting theme in the notebook, that theme has enough color contrast to be legible.
- [ ] Code and code explanations focus on one task at a time. Unless comparison is the point of the notebook, only one method for completing the task is described at a time.

### Images

- [ ] All images (jpg, png, svgs) have an [image description](https://www.w3.org/WAI/tutorials/images/decision-tree/). This could be
    - [ ] [Alt text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt) (an `alt` property) 
    - [ ] [Empty alt text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#decorative_images) for decorative images/images meant to be skipped (an `alt` attribute with no value)
    - [ ] Captions
    - [ ] If no other options will work, the image is decribed in surrounding paragraphs.

- [ ] Any [text present in images](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html) exists in a text form outside of the image (this can be alt text, captions, or surrounding text.)

### Visualizations

- [ ] All visualizations have an image description. Review the previous section, Images, for more information on how to add it.
- [ ] [Visualization descriptions](http://diagramcenter.org/specific-guidelines-e.html) include
    - [ ] The type of visualization (like bar chart, scatter plot, etc.)
    - [ ] Title
    - [ ] Axis labels and range
    - [ ] Key or legend
    - [ ] An explanation of the visualization's significance to the notebook (like the trend, an outlier in the data, what the author learned from it, etc.)

- [ ] All visualizations and their parts have [enough color contrast](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) ([color contrast checker](https://webaim.org/resources/contrastchecker/)) to be legible. Remember that transparent colors have lower contrast than their opaque versions.
- [ ] All visualizations [convey information with more visual cues than color coding](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html). Use text labels, patterns, or icons alongside color to achieve this.
- [ ] All visualizations have an additional way for notebook readers to access the information. Linking to the original data, including a table of the data in the same notebook, or sonifying the plot are all options.

### CODE REVIEW

**Comment by FDauphin** [comment]
Fix for [Scheduled Notebook Execution Failure 55](https://github.com/spacetelescope/hst_notebooks/actions/runs/11309871824/job/31454225951) with following Error:

```
UnitConversionError: 'm / K' and 'Angstrom' (length) are not convertible
```

which comes from `synphot.models` [line 55](https://github.com/spacetelescope/synphot_refactor/blob/master/synphot/models.py#L55):

```
return ((const.b_wien.value / self.temperature) * u.m).to_value(u.AA)
```

where const is `astropy.constants`, self is a `synphot.models.BlackBody1D` object, and u is `astropy.units`

Problem:
- `bb_temp = 5000 * u.K`
- `model = synphot.models.BlackBody1D(bb_temp)`
- In line 55 from above, `const.b_wien.value` is `np.float64`
- `self.temperature` is `astropy.modeling.Parameter('temperature', value=5000, unit=K)`
- In astropy 6.1.2, `const.b_wien.value / self.temperature` is np.float64, not a `Quantity` from `astropy`
- In turn, the above quotient is a float, so it can be multiplied by `u.m` and converted to `u.AA` (Angstroms)
- In astropy 6.1.4, the quotient is a `Quantity` with units 1/K
- When multiplied by `u.m`, it has units m/K, which cannot be converted to Angstroms 

Solution:
- Remove units from `bb_temp`:
  - `bb_temp = 5000`
- All results are nominal with this change
- I assume dividing a float by a `astropy.modeling.Parameter` got resolved to carry units properly in a recent update of astropy

Discussion:
I feel like keeping the unit is more "astro-pythonic", but I couldn't find a solution while keeping the unit. Is there a more optimal solution?

**Comment by FDauphin** [comment]
@haticekaratay This PR passes all checks and is ready for review. @st-apidgeon Is there anything else within your notebook that would cause errors without the `astropy.unit` on `bb_temp`?

**Comment by st-apidgeon** [comment]
@FDauphin it looks like the implementation of Wien's law in Synphot is actually expecting a float. Not sure why it was working before with the unit definition, but I've confirmed that the notebook functions correctly when it is removed.

**Review by haticekaratay — APPROVED** [review]
@FDauphin Thanks for fixing the execution errors.

**Pull request merged**
