### PR TITLE
Updated drizzlepac readme

### PR DESCRIPTION
**Pull request by mrevalski**
The readme file for the DrizzlePac Notebooks has been updated in consultation with Jennifer Mack.

### CODE REVIEW

**Comment by mrevalski** [comment]
Hi @haticekaratay, Jennifer and I have revised the README file to reflect the recent updates to all notebooks. Thank you, and have a great day!

**Comment by mrevalski** [comment]
In addition, we have updated the _toc.yml file so that the notebooks are listed in the same order as the readme. This PR is ready for review as your time allows, have a great weekend!

**Comment by mrevalski** [comment]
I'm unsure why the execution check is failing as we only modified the TOC. Perhaps it's a lingering CI run, but please let us know if a fix is required. Thanks again!

**Review by haticekaratay — APPROVED** [review]
Hi @mrevalski, the failure on the execution is a known issue reported to the CI team. Thanks for organizing the toc and updating the Readme.

**Comment by mackjenn** [comment]
Looks like the [readme HTML](https://spacetelescope.github.io/hst_notebooks/notebooks/DrizzlePac/README.html) is not propagating yet. This seems to be a recurring issue?

**Pull request merged**
