### PR TITLE
Fix and deploy dormant DrizzlePac notebook "align_mosaics.py"

### PR DESCRIPTION
**Pull request by dulude**
**Relevant Ticket**
- [SPB-1704](https://jira.stsci.edu/browse/SPB-1704)

**High-Level Summary**
- For an unknown reason, the _align_mosaics.ipynb_ was added to the hst_notebooks repository but explicitly excluded from being deployed. This PR fixes that issue.

**Summary of Changes**
- align_mosaics.ipynb: added single space in first markdown cell so that CI/CD tests would trigger.
- _config.yml: removed notebook "align_mosaics.ipynb" from "exclude patterns" list
-_toc.yml: uncommented align_mosaics.ipynb line.

-----------
This notebook checklist has been made available to us by the [Notebooks For All team](https://github.com/Iota-School/notebooks-for-all/blob/main/resources/event-hackathon/notebook-authoring-checklist.md).
Its purpose is to serve as a guide for both the notebook author and the technical reviewer highlighting critical aspects to consider when striving to develop an accessible and effective notebook.

### The First Cell

- [ ] The title of the notebook in a first-level heading (eg. `<h1>` or `# in markdown`).
- [ ] A brief description of the notebook.
- [ ] A table of contents in an [ordered list](https://www.markdownguide.org/basic-syntax/#ordered-lists) (`1., 2.,` etc. in Markdown).
- [ ] The author(s) and affiliation(s) (if relevant).
- [ ] The date first published.
- [ ] The date last edited (if relevant).
- [ ] A link to the notebook's source(s) (if relevant).

### The Rest of the Cells

- [ ] There is only one H1 (`#` in Markdown) used in the notebook.
- [ ] The notebook uses other [heading tags](https://www.markdownguide.org/basic-syntax/#headings) in order (meaning it does not skip numbers). 

## Text

- [ ] All link text is descriptive. It tells users where they will be taken if they open the link.
- [ ] All acronyms are defined at least the first time they are used. 
- [ ] Field-specific/specialized terms are used when needed, but not excessively.

## Code

- [ ] Code sections are introduced and explained before they appear in the notebook. This can be fulfilled with a heading in a prior Markdown cell, a sentence preceding it, or a code comment in the code section.
- [ ] Code has explanatory comments (if relevant). This is most important for long sections of code.
- [ ] If the author has control over the syntax highlighting theme in the notebook, that theme has enough color contrast to be legible.
- [ ] Code and code explanations focus on one task at a time. Unless comparison is the point of the notebook, only one method for completing the task is described at a time.

### Images

- [ ] All images (jpg, png, svgs) have an [image description](https://www.w3.org/WAI/tutorials/images/decision-tree/). This could be
    - [ ] [Alt text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt) (an `alt` property) 
    - [ ] [Empty alt text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#decorative_images) for decorative images/images meant to be skipped (an `alt` attribute with no value)
    - [ ] Captions
    - [ ] If no other options will work, the image is decribed in surrounding paragraphs.

- [ ] Any [text present in images](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html) exists in a text form outside of the image (this can be alt text, captions, or surrounding text.)

### Visualizations

- [ ] All visualizations have an image description. Review the previous section, Images, for more information on how to add it.
- [ ] [Visualization descriptions](http://diagramcenter.org/specific-guidelines-e.html) include
    - [ ] The type of visualization (like bar chart, scatter plot, etc.)
    - [ ] Title
    - [ ] Axis labels and range
    - [ ] Key or legend
    - [ ] An explanation of the visualization's significance to the notebook (like the trend, an outlier in the data, what the author learned from it, etc.)

- [ ] All visualizations and their parts have [enough color contrast](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) ([color contrast checker](https://webaim.org/resources/contrastchecker/)) to be legible. Remember that transparent colors have lower contrast than their opaque versions.
- [ ] All visualizations [convey information with more visual cues than color coding](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html). Use text labels, patterns, or icons alongside color to achieve this.
- [ ] All visualizations have an additional way for notebook readers to access the information. Linking to the original data, including a table of the data in the same notebook, or sonifying the plot are all options.

### CODE REVIEW

**Comment by haticekaratay** [comment]
Hello @FDauphin, I am uncertain who was tasked with working on this notebook. I wanted to tag you so that I can inform all the parties involved in this matter and add this to the queue for a technical review. There is an execution error, which can be found here: https://github.com/spacetelescope/hst_notebooks/actions/runs/7744396146/job/21118057705?pr=127.

**Comment by FDauphin** [comment]
> Hello @FDauphin, I am uncertain who was tasked with working on this notebook. I wanted to tag you so that I can inform all the parties involved in this matter and add this to the queue for a technical review. There is an execution error, which can be found here: https://github.com/spacetelescope/hst_notebooks/actions/runs/7744396146/job/21118057705?pr=127.

@haticekaratay Thanks for the heads up. I believe @bjkuhn was tasked with this notebook a few months ago, but we wanted to focus on fully ingesting WFC3 notebooks first. I can chat with him offline about time constraints for fixing this notebook 👍🏾

**Comment by FDauphin** [comment]
@haticekaratay To keep you in the loop, there are a few issues organizationally the INS teams need to address before moving forward with this PR:

1. @mackjenn has noticed several Drizzlepac notebooks aren't working as expected (either code wise or science wise) besides this one. Most notebooks were developed in 2018 and are now most likely stale, causing some errors on both sides. More time than expected will be needed to test them and confirm we are getting expected results before opening additional PRs.
2.  @bjkuhn and I are listed as the current notebook curators for Drizzlepac, but I think it would be preferred if the curator has an in-depth knowledge of Drizzlepac to properly support notebook authors due to the package's complexity. We need to determine if this role is simply a delegator to authors or if they are also responsible for addressing package failure, function deprecation, and unexpected outputs.
3. A few of the Drizzlepac notebooks were developed by people who are no longer within HST, and these notebooks were not properly transitioned to a new author. Some new developers were chosen to fix the notebooks during ingest, but we need to confirm who is responsible for fixes long term (i.e. a new designated author).
4. There is currently no "Drizzlepac" team responsible for maintaining the repository, which makes it difficult to delegate tasks. All the other notebooks naturally fall into instrument teams so a similar structure should be set in place to better support the repository.

@mackjenn and I are working on addressing these issues so for now there is no action needed to be taken on this PR. If it's easier for your team to stop getting CI failure alerts and focus on higher priority PRs, we can close this PR and reopen (or open a new one) when we have a more organized plan. Please let me know if you have any questions, comments, concerns, or clarifications and thanks again for your continuous effort towards this repository 🙂

**Comment by FDauphin** [comment]
@haticekaratay We have decided to close this PR to allow DMD to focus on other higher priority tasks.  We will reach out when we are ready to push the updated Drizzlepac notebooks and requirement texts. Thank you for your patience 🙌🏾

**Pull request closed without merging**
