### PR TITLE
Updated WFC3 readme

### PR DESCRIPTION
**Pull request by mrevalski**
Hi @FDauphin and @haticekaratay,

I have updated the WFC3 README.md file to include the recently merged hst_point_spread_function notebook.

Please let me know if you have any questions!

### CODE REVIEW

**Comment by haticekaratay** [comment]
That's perfect. FYI: Merging this PR won't trigger redeployment to reflect on Github Pages, but I have a workaround for this, as I know the CI team is working on this issue. I'll approve and do a manual deployment.

**Comment by FDauphin** [comment]
> Hi @FDauphin and @haticekaratay,
> 
> I have updated the WFC3 README.md file to include the recently merged hst_point_spread_function notebook.
> 
> Please let me know if you have any questions!

@mrevalski LGTM thanks 👍🏾

**Comment by mrevalski** [comment]
Done and merged! I'm not sure if I should have permissions to merge, perhaps because there were no conflicts? Someone gave me limited write access to view download statistics, so if that should be reverted for safety, please let me know @haticekaratay.

**Comment by haticekaratay** [comment]
No issue at all. Upon approval, you can merge. Glad you did.

**Pull request merged**
