### PR TITLE
Spelling Corrections

### PR DESCRIPTION
**Pull request by mrevalski**
Hi @FDauphin and @haticekaratay,

I've made several spelling corrections to this notebook, and no changes have been made to the code.

Please let me know if you have any questions!

### CODE REVIEW

**Review by FDauphin — APPROVED** [review]
LGTM, nice catch on these 👍🏾

**Comment by mrevalski** [comment]
The CI failure is due to the recent changes in photutils from 1.12 to 1.13, as discussed by Larry Bradley on Slack. photutils is not directly called in this notebook, but a function within custom drizzlepac code I believe, and so should not prevent merging.

**Comment by haticekaratay** [comment]
@mrevalski, let's pin the photutils for now. This should address the execution failure.

**Comment by haticekaratay** [comment]
> Hi @haticekaratay, I've pinned the version of photutils and that solved the CI failure. As with my other recent PR #294 I'm not sure if I should have write access to merge the pull request myself. Or should this be allowed once all changes are approved?

Merging it now.

**Pull request merged**
