### PR TITLE
Add WFC3 notebook  'zeropoints.ipynb'

### PR DESCRIPTION
**Pull request by dulude**
**Relevant Tickets**
- [SPB-1634](https://jira.stsci.edu/browse/SPB-1634)

------

This notebook checklist has been made available to us by the [Notebooks For All team](https://github.com/Iota-School/notebooks-for-all/blob/main/resources/event-hackathon/notebook-authoring-checklist.md).
Its purpose is to serve as a guide for both the notebook author and the technical reviewer highlighting critical aspects to consider when striving to develop an accessible and effective notebook.

### The First Cell

- [ ] The title of the notebook in a first-level heading (eg. `<h1>` or `# in markdown`).
- [ ] A brief description of the notebook.
- [ ] A table of contents in an [ordered list](https://www.markdownguide.org/basic-syntax/#ordered-lists) (`1., 2.,` etc. in Markdown).
- [ ] The author(s) and affiliation(s) (if relevant).
- [ ] The date first published.
- [ ] The date last edited (if relevant).
- [ ] A link to the notebook's source(s) (if relevant).

### The Rest of the Cells

- [ ] There is only one H1 (`#` in Markdown) used in the notebook.
- [ ] The notebook uses other [heading tags](https://www.markdownguide.org/basic-syntax/#headings) in order (meaning it does not skip numbers). 

## Text

- [ ] All link text is descriptive. It tells users where they will be taken if they open the link.
- [ ] All acronyms are defined at least the first time they are used. 
- [ ] Field-specific/specialized terms are used when needed, but not excessively.

## Code

- [ ] Code sections are introduced and explained before they appear in the notebook. This can be fulfilled with a heading in a prior Markdown cell, a sentence preceding it, or a code comment in the code section.
- [ ] Code has explanatory comments (if relevant). This is most important for long sections of code.
- [ ] If the author has control over the syntax highlighting theme in the notebook, that theme has enough color contrast to be legible.
- [ ] Code and code explanations focus on one task at a time. Unless comparison is the point of the notebook, only one method for completing the task is described at a time.

### Images

- [ ] All images (jpg, png, svgs) have an [image description](https://www.w3.org/WAI/tutorials/images/decision-tree/). This could be
    - [ ] [Alt text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt) (an `alt` property) 
    - [ ] [Empty alt text](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#decorative_images) for decorative images/images meant to be skipped (an `alt` attribute with no value)
    - [ ] Captions
    - [ ] If no other options will work, the image is decribed in surrounding paragraphs.

- [ ] Any [text present in images](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html) exists in a text form outside of the image (this can be alt text, captions, or surrounding text.)

### Visualizations

- [ ] All visualizations have an image description. Review the previous section, Images, for more information on how to add it.
- [ ] [Visualization descriptions](http://diagramcenter.org/specific-guidelines-e.html) include
    - [ ] The type of visualization (like bar chart, scatter plot, etc.)
    - [ ] Title
    - [ ] Axis labels and range
    - [ ] Key or legend
    - [ ] An explanation of the visualization's significance to the notebook (like the trend, an outlier in the data, what the author learned from it, etc.)

- [ ] All visualizations and their parts have [enough color contrast](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) ([color contrast checker](https://webaim.org/resources/contrastchecker/)) to be legible. Remember that transparent colors have lower contrast than their opaque versions.
- [ ] All visualizations [convey information with more visual cues than color coding](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html). Use text labels, patterns, or icons alongside color to achieve this.
- [ ] All visualizations have an additional way for notebook readers to access the information. Linking to the original data, including a table of the data in the same notebook, or sonifying the plot are all options.

### CODE REVIEW

**Comment by haticekaratay** [comment]
Hi, the log for the failing execution can be viewed: https://github.com/spacetelescope/hst_notebooks/actions/runs/7253102293/job/19759010856?pr=114
There are also still some style errors that need to be handled: 
https://github.com/spacetelescope/hst_notebooks/actions/runs/7253102295/job/19759004915?pr=114

Thank you!

**Comment by haticekaratay** [comment]
@FDauphin, I reverted the unrelated notebooks from the diff so that only the zeropints notebook changes are visible.

**Comment by st-apidgeon** [comment]
@haticekaratay PEP8 issues for all of my notebooks should be fixed. @FDauphin and I just both ran through this notebook with clean envs and got through it fine, so we are not sure what is causing the execution check to fail.

**Comment by haticekaratay** [comment]
> @haticekaratay PEP8 issues for all of my notebooks should be fixed. @FDauphin and I just both ran through this notebook with clean envs and got through it fine, so we are not sure what is causing the execution check to fail.

@st-apidgeon and @FDauphin . After running the notebook myself and encountering the same issues highlighted in the CI logs, I dove into the error messages a bit deeper. I suspect the issue might be related to file path configurations. Additionally, the errors mention missing 'graph tables,' suggesting a potential misconfiguration or absence of these essential files.

Could we verify the PYSYN_CDBS path to ensure it's correctly set to include all necessary files, especially the 'graph tables'? I'm not as familiar with the scientific specifics, so I'd value your input on this.

**Comment by st-apidgeon** [comment]
@haticekaratay I've been looking over the notebook and I cannot seem to replicate the issue. There should not be any files _missing_, but it is possible there's an issue with the pointing. The only idea I have is to ensure that this notebook is using the exact same import structure as the others to see if that fixes it; it's currently slightly different with respect to the use of the Vega spectrum. I'll try that and if it doesn't work, I may ask you to send over a yml with the environment you're using to test out the notebook to see if that can get the failure to replicate on my end. Thanks for your time spent on this!

**Comment by FDauphin** [comment]
> Hi @st-apidgeon and @FDauphin, For your information, I have fixed the execution error we see in the CI. The issue was caused by importing the `stsynphot` before setting the `PYSYN_CDBS` in the environment. However, I need you to add a comment to the notebook explaining why this is done and make it clear for readers as well. I haven't reviewed the entire notebook yet, but once I do, I'll share my feedback with you. Thank you!

@st-apidgeon @haticekaratay Thank you so much for solving this; it's deeply appreciated. Sounds like an easy comment on our end 👍🏾

**Comment by st-apidgeon** [comment]
Hi @haticekaratay thanks very much! Also really appreciate it. I'll add the comment asap.

**Comment by FDauphin** [comment]
@haticekaratay Comment has been addressed and all checks have passed; we should be good for merge 👍🏾

**Review by haticekaratay — APPROVED** [review]
I have updated a couple of minor things in the notebook. All looks good to me!

**Pull request merged**
