### PR TITLE
Debugging and updating the Drizzlepac mask_satellite notebook

### PR DESCRIPTION
**Pull request by annierose3**
Updating imports from new version of acstools 3.6.1, which includes vital updates to skimage functionality. Also adding a few minor updates to allow images to be displayed correctly. I have updated the requirements.txt to reflect the use of a new acstools version 3.6.1

### CODE REVIEW

**Comment by dulude** [comment]
LGTM but I can't approve the merge until I find out from Erik T. next week if this has to go through the full technical review process.

**Comment by dulude** [comment]
I'm not sure why the notebook code PEP8 style checker didn't run, but it can be run manually. It looks like there are 10 PEP8 style issues that need to be fixed:
`$ python .github/helpers/pep8_nb_style_checker.py -f /Users/dulude/Documents/GitHub/hst_notebooks/notebooks/DrizzlePac/mask_satellite/mask_satellite.ipynb
PEP8 error 1 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 6, column 1
from astropy.visualization import astropy_mpl_style,LogStretch,ImageNormalize,LinearStretch
▲
F401 'astropy.visualization.LogStretch' imported but unused

PEP8 error 2 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 6, column 52
from astropy.visualization import astropy_mpl_style,LogStretch,ImageNormalize,LinearStretch
                                                   ▲
E231 missing whitespace after ','

PEP8 error 3 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 6, column 63
from astropy.visualization import astropy_mpl_style,LogStretch,ImageNormalize,LinearStretch
                                                              ▲
E231 missing whitespace after ','

PEP8 error 4 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 6, column 78
from astropy.visualization import astropy_mpl_style,LogStretch,ImageNormalize,LinearStretch
                                                                             ▲
E231 missing whitespace after ','

PEP8 error 5 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 11, column 1
import acstools
▲
F401 'acstools' imported but unused

PEP8 error 6 of 10
PEP8 error found in code cell 2 (Notebook cell 6) at code cell line 1, column 1
#Searching for the observsation
▲
E265 block comment should start with '# '

PEP8 error 7 of 10
PEP8 error found in code cell 2 (Notebook cell 6) at code cell line 4, column 1
#Downloading previews and FLC files
▲
E265 block comment should start with '# '

PEP8 error 8 of 10
PEP8 error found in code cell 3 (Notebook cell 7) at code cell line 7, column 8
       os.rename(file, os.path.basename(file))
       ▲
E111 indentation is not a multiple of 4

PEP8 error 9 of 10
PEP8 error found in code cell 3 (Notebook cell 7) at code cell line 7, column 8
       os.rename(file, os.path.basename(file))
       ▲
E117 over-indented

PEP8 error 10 of 10
PEP8 error found in code cell 11 (Notebook cell 22) at code cell line 10, column 7
    dq  = hdu[6].data
      ▲
E221 multiple spaces before operator
`

**Review by dulude — CHANGES_REQUESTED** [review]
I'm not sure why the notebook code PEP8 style checker didn't run, but it can be run manually. It looks like there are 10 PEP8 style issues in the python code imbedded in the mask_satellite.ipynb notebook that need to be fixed:
```
~/Documents/SPB/notebooks/hst_notebooks $ python .github/helpers/pep8_nb_style_checker.py -f /Users/dulude/Documents/GitHub/hst_notebooks/notebooks/DrizzlePac/mask_satellite/mask_satellite.ipynb
PEP8 error 1 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 6, column 1
from astropy.visualization import astropy_mpl_style,LogStretch,ImageNormalize,LinearStretch
▲
F401 'astropy.visualization.LogStretch' imported but unused

PEP8 error 2 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 6, column 52
from astropy.visualization import astropy_mpl_style,LogStretch,ImageNormalize,LinearStretch
                                                   ▲
E231 missing whitespace after ','

PEP8 error 3 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 6, column 63
from astropy.visualization import astropy_mpl_style,LogStretch,ImageNormalize,LinearStretch
                                                              ▲
E231 missing whitespace after ','

PEP8 error 4 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 6, column 78
from astropy.visualization import astropy_mpl_style,LogStretch,ImageNormalize,LinearStretch
                                                                             ▲
E231 missing whitespace after ','

PEP8 error 5 of 10
PEP8 error found in code cell 1 (Notebook cell 4) at code cell line 11, column 1
import acstools
▲
F401 'acstools' imported but unused

PEP8 error 6 of 10
PEP8 error found in code cell 2 (Notebook cell 6) at code cell line 1, column 1
#Searching for the observsation
▲
E265 block comment should start with '# '

PEP8 error 7 of 10
PEP8 error found in code cell 2 (Notebook cell 6) at code cell line 4, column 1
#Downloading previews and FLC files
▲
E265 block comment should start with '# '

PEP8 error 8 of 10
PEP8 error found in code cell 3 (Notebook cell 7) at code cell line 7, column 8
       os.rename(file, os.path.basename(file))
       ▲
E111 indentation is not a multiple of 4

PEP8 error 9 of 10
PEP8 error found in code cell 3 (Notebook cell 7) at code cell line 7, column 8
       os.rename(file, os.path.basename(file))
       ▲
E117 over-indented

PEP8 error 10 of 10
PEP8 error found in code cell 11 (Notebook cell 22) at code cell line 10, column 7
    dq  = hdu[6].data
      ▲
E221 multiple spaces before operator
```

**Comment by camipacifici** [comment]
@dulude @haticekaratay this does not need to go through formal technical review at this time. Feel free merge when ready.

**Pull request merged**
